language: node_js 
sudo: required 
cache: 
  yarn: true 
  directories: 
    - node_modules 
services:
  - docker
addons: 
  apt: 
    sources:
      - google-chrome 
    packages: 
      - google-chrome-stable 
node_js: 
  - "10.8.0" 
before_install: 
  - npm install -g yarn
install: 
  - yarn install
script: 
  - yarn provision
  - curl -s http://128.199.101.218:7001/ci
