version: "2"

services:
  frontend:
    container_name: "boilerplate"
    build: .
    environment:
      NODE_ENV: "developments"
      REACT_APP_API_URL: "http://localhost:3000"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

networks:
  default:
    external:
      name: boilerplate