/* GENERATED BY REDUX-GENERATOR */
const TYPE = "selected_pendukung"

class SelectedPendukungAction {
  static elements(element) {
    return {
      type: TYPE,
      value: element
    }
  }
}
export default SelectedPendukungAction;
export { TYPE };