/* GENERATED BY REDUX-GENERATOR */
const TYPE = "Users"

class UsersAction {
  static elements(element) {
    return {
      type: TYPE,
      value: element
    }
  }
}
export default UsersAction;
export { TYPE };