/* GENERATED BY REDUX-GENERATOR */
import { TYPE } from "../action/selected_pendukung_action";

class SelectedPendukungReducer {
  static elements(state, action) {
    return ({
      ...state,
      ...action.value
    });
  }

  static reduce(state = {}, action = {}) {
    switch(action.type) {
      case TYPE:
        return action.value
      default:
        return state;
    }
  }
}
export default SelectedPendukungReducer;